AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a NAT Gateway'

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the NAT Gateway will be created

  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the public subnet where the NAT Gateway will be created

  NatGatewayName:
    Type: String
    Description: The name to be assigned to the NAT Gateway
    Default: 'MyNATGateway'

Resources:
  NatGatewayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${NatGatewayName}-EIP'

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGatewayEIP.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: !Ref NatGatewayName

Outputs:
  NatGatewayId:
    Description: The ID of the created NAT Gateway
    Value: !Ref NatGateway
    Export:
      Name: !Sub '${AWS::StackName}-NatGatewayId'

  NatGatewayEIP:
    Description: The Elastic IP address associated with the NAT Gateway
    Value: !Ref NatGatewayEIP
    Export:
      Name: !Sub '${AWS::StackName}-NatGatewayEIP'
