AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create a Multi-AZ Aurora Serverless v2 cluster using SSM for username and password'

Parameters:
  DBClusterName:
    Type: String
    Description: The name of the Aurora Serverless v2 cluster

  DBClusterParameterGroupName:
    Type: String
    Description: The name of the DB cluster parameter group
    Default: default.aurora-mysql8.0

  DBSubnetGroupName:
    Type: String
    Description: The name of the DB subnet group

  VpcSecurityGroupIds:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: The list of VPC security group IDs to associate with the cluster

  DatabaseName:
    Type: String
    Description: The name of the database to create

  MasterUsernameParameterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The name of the SSM parameter that stores the master username

  MasterUserPasswordParameterName:
    Type: AWS::SSM::Parameter::Value<String>
    Description: The name of the SSM parameter that stores the master user password

Resources:
  DBCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: 8.0.32
      DBClusterParameterGroupName: !Ref DBClusterParameterGroupName
      DBSubnetGroupName: !Ref DBSubnetGroupName
      DatabaseName: !Ref DatabaseName
      MasterUsername: !Ref MasterUsernameParameterName
      MasterUserPassword: !Ref MasterUserPasswordParameterName
      VpcSecurityGroupIds: !Ref VpcSecurityGroupIds
      DeletionProtection: false
      ServerlessV2ScalingConfiguration:
        MinCapacity:
          ACU: 0.5
        MaxCapacity:
          ACU: 128
      EnableHttpEndpoint: true

Outputs:
  DBClusterEndpoint:
    Description: The endpoint for the Aurora Serverless v2 cluster
    Value: !GetAtt DBCluster.Endpoint.Reader

  DBClusterReadEndpoint:
    Description: The reader endpoint for the Aurora Serverless v2 cluster
    Value: !GetAtt DBCluster.ReadEndpoint.Address

  DBClusterHttpEndpoint:
    Description: The HTTP endpoint for the Aurora Serverless v2 cluster
    Value: !GetAtt DBCluster.HttpEndpoint
