AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating an Application Load Balancer'

Parameters:
  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the first public subnet
  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: The ID of the second public subnet
  LoadBalancerName:
    Type: String
    Description: The name of the Application Load Balancer
  Scheme:
    Type: String
    AllowedValues:
      - internet-facing
      - internal
    Default: internet-facing
    Description: The scheme for the Application Load Balancer (internet-facing or internal)
  IpAddressType:
    Type: String
    AllowedValues:
      - ipv4
      - dualstack
    Default: ipv4
    Description: The IP address type for the Application Load Balancer
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the Application Load Balancer will be created
  SecurityGroupList:
    Type: List<AWS::EC2::SecurityGroup::Id>
    Description: A list of Security Groups for the Application Load Balancer

Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Ref LoadBalancerName
      Scheme: !Ref Scheme
      IpAddressType: !Ref IpAddressType
      SecurityGroups: !Ref SecurityGroupList
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Type: application

Outputs:
  LoadBalancerDNS:
    Description: The DNS name of the Application Load Balancer
    Value: !GetAtt ApplicationLoadBalancer.DNSName


# Question used in Amazon Q

  #can you help me generate cloudformation template for application load balancer that allows user to input the following parameters and output the load balancer's DNS?
 # The parameters for the cloudformation template:

 # Public Subnet 1 with the type of AWS::EC2::Subnet::Id

 # Public Subnet 2 with the type of AWS::EC2::Subnet::Id

 # Load Balancer Name

 # Scheme parameter that allows user to define if the application load balancer is internet-facing or internal

 # Load Balancer IP Address Type

 # VPC id and its mapping of subnet

#  Security Group

#There are hardcoding in the mapping section to fill in the subnet id in Project VPC